name: FantasiaPainter
favicon: null
layout_spectrum: 0.92006
typography_spectrum: 0.31587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#15285a'
    - '#374883'
    - '#5e7fc7'
    - '#a5a5c5'
  brandStrength: 0.625
  lightness: 0.5712351237889379
  saturation: 0.20143892616033554
  rhythmicContrast: 0.9129625877831131
purpose: []
